### ISSUE TITLE
Nothing was returned from render error while trying to implement with React

### ISSUE THREAD

**Issue by avinashsivaraman** [developit/stockroom#6]
I am trying to implement the basic counter using React but getting the below error

> invariant.js:42 Uncaught Error: p(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
>     at invariant (invariant.js:42)
>     at reconcileChildFibers (react-dom.development.js:7688)
>     at reconcileChildrenAtExpirationTime (react-dom.development.js:7756)
>     at reconcileChildren (react-dom.development.js:7747)
>     at mountIndeterminateComponent (react-dom.development.js:8075)
>     at beginWork (react-dom.development.js:8221)
>     at performUnitOfWork (react-dom.development.js:10224)
>     at workLoop (react-dom.development.js:10288)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:542)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:581)

**Comment by avinashsivaraman** [comment]
Index.js

![screen shot 2018-01-25 at 4 15 05 pm](https://user-images.githubusercontent.com/7939589/35384354-fe7678e6-01ea-11e8-844d-4b7fb6d1d3c3.png)

**Comment by hamczu** [comment]
Probably the real issue lives here: https://github.com/developit/unistore/issues/50

**Comment by developit** [comment]
I just released unistore 3.0.4, which fixes this issue in both libraries:
https://github.com/developit/unistore/releases/tag/3.0.4

**Comment by hamczu** [comment]
Hm... after that update I have different error (trying to run the demo):
`index.js:1 Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': ({ count }) => ({ count: count + 1 }) could not be cloned.`

**Comment by developit** [comment]
@hamczu thanks, seeing that too - looking into it now.

**Comment by anisht42** [comment]
![image](https://user-images.githubusercontent.com/37433973/62056858-1ca70300-b23c-11e9-83e5-50b729401eae.png)


when i try to connect with Redux with React-native application, getting this issue. Any idea please?
